apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    move2kube.konveyor.io/service.expose: "true"
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: highwide
  name: highwide
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: quay.io/yc25z/highwide:latest
          imagePullPolicy: Always
          name: highwide
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
